name: Render and Publish

on:
  push:
    branches: [main, master]
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: false
          
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::readr
            any::dplyr
            any::stringr
            any::knitr
            any::kableExtra
            
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
          
      - name: Deplo
